server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Muhasheikh/Microservice-config-store
          search-paths:
          - 'service-config/*service'
          #username: root
          #passphrase: 12345